# Generated by Django 5.1.2 on 2024-11-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0001_initial"),
        ("trucks", "0001_initial"),
        ("userwork", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(null=True)),
                ("points", models.ManyToManyField(to="gps.gpspoint")),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trucks.truck"
                    ),
                ),
            ],
        ),
    ]
