# Generated by Django 5.1.2 on 2024-10-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userwork", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
    ]
