# Generated by Django 5.1.2 on 2024-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userwork", "0002_plannedshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedshift",
            name="was_active",
            field=models.BooleanField(default=False),
        ),
    ]
