# Generated by Django 5.1.2 on 2024-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userwork", "0003_plannedshift_was_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedshift",
            name="end_time",
            field=models.DateTimeField(),
        ),
    ]
