# Generated by Django 5.1.2 on 2024-11-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0001_initial"),
        ("userwork", "0004_alter_plannedshift_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plannedshift",
            name="points",
        ),
        migrations.CreateModel(
            name="PlannedShiftPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "gps_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gps.gpspoint"
                    ),
                ),
                (
                    "planned_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userwork.plannedshift",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="plannedshift",
            name="new_points",
            field=models.ManyToManyField(
                through="userwork.PlannedShiftPoint", to="gps.gpspoint"
            ),
        ),
    ]
