# Generated by Django 5.1.2 on 2024-11-20 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userwork", "0005_remove_plannedshift_points_plannedshiftpoint_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plannedshift",
            old_name="new_points",
            new_name="points",
        ),
    ]
