# Generated by Django 5.1.2 on 2024-11-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GpsPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(decimal_places=6, default=None, max_digits=8),
                ),
                (
                    "long",
                    models.DecimalField(decimal_places=6, default=None, max_digits=8),
                ),
                (
                    "qr_code",
                    models.CharField(default=None, max_length=255, unique=True),
                ),
                ("name", models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
