# Generated by Django 5.1.2 on 2024-11-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GpsPointList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default=None, max_length=100)),
                ("point_set", models.ManyToManyField(to="gps.gpspoint")),
            ],
        ),
    ]
